### ISSUE TITLE
Lage prosjekt-/kanban-mal for bruk til metode for områdeprofiler

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/no-domain#19]
Formålet er at det skal være oversiktlig og lett å spore fremgang i utvikling av nasjonale områdeprofiler på GitHub.

**Comment by thomiz** [comment]
Forslag til prosjektmal:
https://github.com/HL7Norway/no-domain/projects/2

Det aktive vital-signs prosjektet ligger nå her: 
https://github.com/hn-fresk/hnvitalsigns/projects/1

**Comment by thomiz** [comment]
Da ligger prosjektet på https://github.com/HL7Norway/no-domain/projects/2
hn-fresk prosjektet er lukket
