### ISSUE TITLE
Førsteutkast metode for utvikling av områdeprofiler

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/no-domain#6]
En modifisering av utviklingsprosessen for dagens Ehelse-standarder tilpasset områdeprofiler. Metoden bør fungere godt med f.eks. kanban slik at det kan kjøres her på GitHub for full transparens. Spesielt viktig er det at områdeprofiler kjøres gjennom viktige QA-punkter, som innspillsrunder med sektor, kodeverk og terminologi, sjekk mot internasjonale IGer og prinsippene forøvrig. Hvert sjekkpunkt trenger ikke ha en egen kanban-kolonne, men kan samles i egnede bolker. 

Kjør debatt!

**Comment by rockphotog** [comment]
![CD8697A1-6A37-4FC5-AD45-DBD25503570B](https://user-images.githubusercontent.com/5932885/81744274-48316c00-94a3-11ea-9512-54e8e99fc341.jpeg)

**Comment by oaassv** [comment]
Forslag prinsipper levert.
